config/routes.rb
Groupme::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'groups#index'

    resources :groups do
  	member do
  		post :join
  		post :quit
  	end
  	resources :posts
    end

end

app/models/group.rb
class Group < ActiveRecord::Base

	has_many :posts
	validates :title, :presence => true
	belongs_to :owner, :class_name => "User", :foreign_key => :user_id


	has_many :group_users
	has_many :members, :through => :group_users, :source => :group




	def editable_by?(user)
		user && user == owner
	end


end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base

	belongs_to :group
	belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :group, :counter_cache => true
	validates :content, :presence => true
	belongs_to :author, :class_name => "User", :foreign_key => :user_id

	def editable_by?(user)
		user && user == author
	end


end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  has_many :groups
  has_many :posts

  has_many :group_users
  has_many :participated_groups, :through => :group_users, :source => :group

  
  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable


  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end

  def is_member_of?(group)
    participated_groups.include?(group)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

    before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html  {
          authenticate_user!
        }
        format.js{
          render :partial => "common/not_logined"
        }
        format.all {
          head(:unauthorized)
        }
      end
    end
  
  end


  def require_is_admin
    unless (current_user && current_user.admin?)
      redirect_to root_path, :flash => { :error => "no permission" }
    end
  end

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}
  end

  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	#限定某些特定頁面允許被瀏覽
	before_action :login_required, :only => [:new, :create, :edit, :update, :destroy]


	def index
		@groups = Group.all
	end

	def show
	    @group = Group.find(params[:id])
	    @posts = @group.posts
	end

	def new
		@group = Group.new
	end

	def create
		@group = current_user.groups.build(group_params)

		if @group.save
			#current_user.join!(@group)
			redirect_to groups_path
		else
			render :new
		end
	end

	def edit
		@group = current_user.groups.find(params[:id])
	end

	def update
		@group = current_user.groups.find(params[:id])

		if @group.update(group_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end

	def destroy
		@group = current_user.groups.find(params[:id])

		@group.destroy

		redirect_to groups_path
	end


  def join
    @group = Group.find(params[:id])
    if !current_user.is_member_of?(@group) 
      current_user.join!(@group)
    else
      flash[:warning] = "You already joined this group."
    end
    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])
    if current_user.is_member_of?(@group)
     current_user.quit!(@group)
    else
      flash[:warning] = "You are not member of this group."
    end
    redirect_to group_path(@group)
  end




private

def group_params
	params.require(:group).permit(:title, :description)
end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_group
	before_action :login_required, :only => [:new, :create, :edit, :update, :destroy]
	before_action :member_required, :only => [:new, :create]

	def new 
		@post = @group.posts.build
	end

	def create
		@post = @group.posts.new(post_params)
		@post.author = current_user

		if @post.save
			redirect_to group_path(@group)
		else
			render :new
		end
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end

	def update
		@post = current_user.posts.find(params[:id])

		if @post.update(post_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end

	def destroy
		@post = current_user.posts.find(params[:id])

		@post.destroy

		redirect_to group_path(@group)
	end


	private

	def post_params
		params.require(:post).permit(:content)
	end

	def find_group
		@group = Group.find(params[:group_id])
	end	

	def member_required
		if !current_user.is_member_of?(@group)
			flash[:warning] = "You are not member of this group!"
			redirect_to group_path(@group)
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <%= render_list :class => "nav nav-pills pull-right" do |li|
      #li << link_to( "Link1", "#")
      #li << link_to( "Link2", "#")   
      #li << link_to( "Link3", "#")
      #li << link_to( "Link4", "#")
  end %>
  <p class="copyright">Copyright @2012 <%= Setting.app_name %> All rights reserved.</p>

</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.erb
<div class="navbar navbar-fixed-top ">
      <div class="navbar-inner top ">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to(Setting.app_name, Setting.domain , :class => "brand" )%>

          <%= render :partial => "common/search_form" %>

   
     
          <div class="nav-collapse">
      
              <%= render_list :class => "nav" do |li|
                li << link_to("Link-1","#")
                li << link_to("Link-2","#")
                li << link_to("Link-3","#")
              end %>
              
              <%= render :partial => "common/user_nav"%>

          </div>
    </div>
  </div>

  <%= yield :submenu %>

</div>

app/views/common/_not_logined.js.erb
if (confirm("Please login first, proceed?") )
{
	window.location = "/users/sign_in";
}

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">

    <li>
      <div class="social"> <%=  fb_like(Setting.domain) %>  </div>
    </li>

  <% if current_user %>    

    <li class="dropdown">
      <%= link_to "/account" , :class => "dropdown-toggle", :data => { :toggle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>

      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout",destroy_user_session_path, :method => :delete )
      end %>

    </li>

<% else %>
  <li> <%= link_to( "Sign Up" ,new_user_registration_path) %> </li>
  <li> <%= link_to( "Login", new_user_session_path )  %> </li>   
  <li> <%= link_to( "FB Login", "/users/auth/facebook" )  %> </li>   
<% end %>


</ul>

app/views/groups/edit.html.erb
<div class="span12">

	<%= simple_form_for @group do |f| %>

		<%= f.input :title, :input_html => { :class => "input-xxlarge" } %>
		<%= f.input :description, :input_html => { :class => "input-xxlarge" } %>

		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
		</div>

		<% end %>
</div>

app/views/groups/index.html.erb
<div class="span12">
	<div class="group">
		<%= link_to("New group",new_group_path, :class => "btn btn-mini btn-primary pull-right" ) %>
	</div>

	<table class="table">
		<thead>
			<tr>
				<td> # </td>
				<td> Title </td>
				<td> Descroption </td>
				<td> Owner </td>
			</tr>
		</thead>

		<tbody>
			<% @groups.each do |group| %>
			<tr>
				<td> # </td>
				<td> <%= link_to(group.title, group_path(group)) %> </td>
				<td> <%= group.description %> </td>
				<td> <%= group.owner.name %> </td>
				<td> 
					<% if current_user && group.editable_by?(current_user) %>
					<%= link_to("Edit", edit_group_path(group), :class => "btn btn-mini") %> 
					<%= link_to("Delete", group_path(group), :class => "btn btn-mini", 
									:method => :Delete, :confirm => "Are you sure?") %> 
					<% end %>
				</td>

			</tr>

			<% end %>

		</tbody>

	</table>

</div>

app/views/groups/new.html.erb
<div class="span12">
	<%= simple_form_for @group do |f| %>
		<%= f.input :title, :title_html => { :class => "input-xxlarge"} %>
		<%= f.input :description, :title_html => { :class => "input-xxlarge"} %>

		<div class="form-actions">
			<%= f.submit "Submin", :disable_with => 'Submining...', :class => "btn btn-primary" %>
		</div>
	<% end %>
</div>

app/views/groups/show.html.erb
<div class="span12">
  <div class="group pull-right">

    <% if current_user %>

	    <% if current_user.is_member_of?(@group) %>
	      <%= link_to("Quit Group", quit_group_path(@group), :method => :post, :class=>"btn btn-mini")%>

	    <% else %>
	    <%= link_to("Join Group", join_group_path(@group), :method => :post,  :class=>"btn btn-mini")%> 
	    <% end %>

	    <%= link_to("New Post", new_group_post_path(@group) , :class => "btn btn-mini btn-primary") if current_user.is_member_of?(@group)%>


	    <% if current_user && @group.editable_by?(current_user) %>
	      <%= link_to("Edit", edit_group_path(@group) , :class => "btn btn-mini " )%>
	    <% end %>

    <% end %>
    &nbsp;


  </div>

	<h2> <%= @group.title %> </h2>
	<p>	<%= @group.description %> </p>

	<table class ="table">

		<tbody>
			<% @posts.each do |post| %>
			<tr>
				<td> 
					<span class="author"> <strong> Author：<%= post.author.name %> </strong> </span>
					<p>
					<%= post.content %> 
					</p>
				</td>

				<% if current_user && post.editable_by?(current_user) %>
				<td> <%= link_to("Edit", edit_group_post_path(post.group, post), :class => "btn btn-mini") %>
					 <%= link_to("Delete", group_post_path(post.group, post), :class => "btn btn-mini", :method => :delete, :confirm => "Are you sure?") %>
				</td>
			</tr>

			<% end %>
			<% end %>
		</tbody>
	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

<%= render :partial => "common/menu" %>

  <div class="container">

      <%= notice_message %>

      <div class="content">
        <div class="row">
          <%= yield %>
          <%= yield (:sidebar) %>
        </div> 
    
      </div>

      <%= render :partial => "common/footer" %>    
  </div>



  

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>

  <%= yield :javascripts %>


</body>
</html>

app/views/pages/welcome.html.erb
<div class="span12">
	<h1> Welcome </h1>
</div>

app/views/posts/new.html.erb
<div class="span12">

	<%= simple_form_for [@group,@post] do |f| %>

		<%= f.input :content, :input_html => {:class => "input-xxlarge"} %>

		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
		</div>

		<% end %>

</div>

app/views/posts/post.html.erb
<div class="span12">

	<%= simple_form_for [@group,@post] do |f| %>

		<%= f.input :content, :input_html => {:class => "input-xxlarge"} %>

		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
		</div>

		<% end %>

</div>